### PR TITLE
Created Contact Page

### LINKED ISSUE #6: Create Contact Page
I intend to integrate an api to send data collected directly to your email address.
I intend to build with framer motion.
Can i be assigned this issue?

### PR DESCRIPTION
**Pull request by Onyelaudochukwuka**
Close #6

### CODE REVIEW

**Comment by aditya-singh9** [comment]
There are some errors occuring while building the project can you please look into them

**Comment by aditya-singh9** [comment]
There are some errors occuring while building the project for preview
Please look into them and fix it

**Comment by Onyelaudochukwuka** [comment]
Ooh, I'll fix that

**Comment by aditya-singh9** [comment]
Please add my email in the email section

aditya0930singh@gmail.com 

And remove the phone number section as i do not want to give it to public.

And in the location one
Add 
New Delhi, India

**Comment by Onyelaudochukwuka** [comment]
> Please add my email in the email section
> 
> [aditya0930singh@gmail.com](mailto:aditya0930singh@gmail.com)
> 
> And remove the phone number section as i do not want to give it to public.
> 
> And in the location one Add New Delhi, India

Done Also fixed the navbar for mobile devices

**Pull request merged**
